name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:all

      - name: Build
        run: npm run build:all

      - name: Test
        run: npm run test:all
        env:
          CHROME_BIN: /usr/bin/google-chrome
